### ISSUE TITLE
Redirects on `update` routes

### ISSUE THREAD

**Issue by sternj** [CCExtractor/ccsync#51]
Having the POST endpoints return redirects leads to raised 400 errors when called from app

**Comment by SGI-CAPP-AT2** [comment]
Yes, I understood the problem. 

Problem (I think is):
These handlers are redirecting to `/tasks` since `/tasks` is `GET` endpoint it expects values as parameters. Because these params are empty it sends `400`.

I'll work on same issue and will raise PR soon.

cc: @its-me-abhishek

**Comment by its-me-abhishek** [comment]
hey, i was working already on this, have fixed it.
the issue primarily lied in:
- uuid did not seem to work in Both Edit/Modify Task Requests, so I have updated them on the backend, yet to update in the app
- also the redirects have been removed as they were unnecessary
