### ISSUE TITLE
ModifyTaskInTaskwarrior has wrong conditionals for updates

### ISSUE THREAD

**Issue by sternj** [CCExtractor/ccsync#52]
`escapedStatus` is checked against `"completed"` and `"deleted"`, when the `sprintf` that creates it prepends `status:`

**Comment by SGI-CAPP-AT2** [comment]
It means `status` is `""` (nothing) still the `escapedStatus` is being check and it should be avoided.
Am I right @sternj ?

**Comment by SGI-CAPP-AT2** [comment]
```go
	escapedStatus := fmt.Sprintf(`status:%s`, strings.ReplaceAll(status, `"`, `\"`))
	if escapedStatus == "completed" {
		cmd = exec.Command("task", taskuuid, "done", "rc.confirmation=off")
		cmd.Run()
	} else if escapedStatus == "deleted" {
		cmd = exec.Command("task", taskuuid, "delete", "rc.confirmation=off")
		cmd.Run()
	}
```
Yes so, It should use `status` here instead of `escapedStatus`.

**Comment by SGI-CAPP-AT2** [comment]
Is this issue open for all @sternj ?

**Comment by SGI-CAPP-AT2** [comment]
yes

**Comment by SGI-CAPP-AT2** [comment]
What do you think about this (https://github.com/CCExtractor/ccsync/issues/52#issuecomment-2482140387) ?
@its-me-abhishek

**Comment by its-me-abhishek** [comment]
i have assigned this to you..
> What do you think about this (https://github.com/CCExtractor/ccsync/issues/52#issuecomment-2482140387) ?

this seems to be correct, either you can replace with status, or prepend a 'status:' in the escapedStatus check

**Comment by SGI-CAPP-AT2** [comment]
@its-me-abhishek 
I've made changes.

**Comment by SGI-CAPP-AT2** [comment]
@its-me-abhishek 
While docker compose up I am getting following error.
How can I resolve ? , beacause I've followed all setup form [here](https://its-me-abhishek.github.io/ccsync-docs/api_documentation/)
Error: 
```
PS D:\CCExtractor Repos\ccsync> docker-compose up

[+] Running 1/1
 ✘ syncserver Error pull access denied for taskchampion-sync-server, repository does not exist or may require...                   2.2s 
Error response from daemon: pull access denied for taskchampion-sync-server, repository does not exist or may require 'docker login'
```
