### ISSUE TITLE
bug: (frontend) `/home` footer links under community does not work

### ISSUE THREAD

**Issue by SGI-CAPP-AT2** [CCExtractor/ccsync#56]
The Links in Footer for community of page on route `/home` does not redirect to desired web page.
Screenshot:
![image](https://github.com/user-attachments/assets/5f07fd6b-b64e-464a-a765-388be989b61f)

**Comment by SGI-CAPP-AT2** [comment]
@its-me-abhishek I would like to work on this issue

**Comment by its-me-abhishek** [comment]
this has been left intentionally, will update it later on once we are sure what URLs to add to the discord, slack hyperlinks
