### ISSUE TITLE
Make the backend modular

### ISSUE THREAD

**Issue by its-me-abhishek** [CCExtractor/ccsync#58]
- Create separate files (and folders, if required) for different backend functions
- Update tests for the same
- Separate different Taskwarrior functions, data models, etc.

**Comment by SGI-CAPP-AT2** [comment]
Can I work on it?

**Comment by SGI-CAPP-AT2** [comment]
Hey @its-me-abhishek , I have done setup and gone through all code
and will like to make modifications as follows
```
.
└── backend/
    ├── models/
    │   └── ... all structs
    ├── utils/
    │   └── ...all utility functions like GenerateUUID and repeated code blocks
    │   └── tw/
    │       └── ...taskwarrior commands utilities
    ├── tests/
    │   └── ... all test functions
    ├── controllers/
    │   └── ... all request handlers
    ├── routes.go .. all routes 
    └── main.go ... main func
 ```
I'll make modifications  
will make PR once you confirm.
if you have any feedback, please let me know.
